Repository haedal-uni/dangdang, pull requests merged in 2021-12, with the labels that each got.

#43 Feature/upload
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/shop/dangdang/DangDangApplication.java
  src/main/java/shop/dangdang/config/AmazonS3Config.java
  src/main/java/shop/dangdang/controller/FrontController.java
  src/main/java/shop/dangdang/controller/RegistryController.java
  src/main/java/shop/dangdang/domain/Membership.java
  src/main/java/shop/dangdang/domain/Registry.java
  src/main/java/shop/dangdang/domain/Timestamped.java
  src/main/java/shop/dangdang/dto/MembershipDto.java
  src/main/java/shop/dangdang/dto/RegistryDto.java
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/repository/RegistryRepository.java
  src/main/java/shop/dangdang/service/MembershipService.java
  src/main/java/shop/dangdang/service/RegistryService.java
  src/main/java/shop/dangdang/service/S3Uploader.java
  src/main/resources/application.properties
  src/main/resources/static/images/background01.png
  src/main/resources/static/images/img_section/coco.jpg
  src/main/resources/static/images/img_section/img03.jpg
  src/main/resources/static/images/temp.png
  src/main/resources/static/images/thumb.jpeg
  src/main/resources/static/images/thumb02.jpg
  src/main/resources/static/images/thumb03.jpg
  src/main/resources/static/index.html
  src/main/resources/static/registry.html
  src/main/resources/static/styles/button.css
  src/main/resources/static/styles/common.css
  src/main/resources/static/styles/detail.css
  src/main/resources/static/styles/reset.css
  src/main/resources/static/styles/style.css
  src/test/java/com/sparta/dangdang/DangdangApplicationTests.java
Labels: develop, backend

#46 Main
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/com/sparta/dangdang/DangDangApplication.java
  src/main/java/shop/dangdang/DangDangApplication.java
  src/main/java/shop/dangdang/config/AmazonS3Config.java
  src/main/java/shop/dangdang/config/WebConfig.java
  src/main/java/shop/dangdang/controller/FeedDetailController.java
  src/main/java/shop/dangdang/controller/FrontController.java
  src/main/java/shop/dangdang/controller/RegistryController.java
  src/main/java/shop/dangdang/domain/Comment.java
  src/main/java/shop/dangdang/domain/Feed.java
  src/main/java/shop/dangdang/domain/FeedLikeUser.java
  src/main/java/shop/dangdang/domain/Membership.java
  src/main/java/shop/dangdang/domain/Registry.java
  src/main/java/shop/dangdang/domain/Timestamped.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/dto/CommentResponseDto.java
  src/main/java/shop/dangdang/dto/CommonMsgResponseDto.java
  src/main/java/shop/dangdang/dto/FeedDetailResponseDto.java
  src/main/java/shop/dangdang/dto/FeedLikeRequestDto.java
  src/main/java/shop/dangdang/dto/FeedLikeResponseDto.java
  src/main/java/shop/dangdang/dto/MembershipDto.java
  src/main/java/shop/dangdang/dto/RegistryDto.java
  src/main/java/shop/dangdang/repository/CommentRepository.java
  src/main/java/shop/dangdang/repository/FeedLikeUserRepository.java
  src/main/java/shop/dangdang/repository/FeedRepository.java
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/repository/RegistryRepository.java
  src/main/java/shop/dangdang/repository/UserRepository.java
  src/main/java/shop/dangdang/service/FeedDetailService.java
  src/main/java/shop/dangdang/service/MembershipService.java
  src/main/java/shop/dangdang/service/RegistryService.java
  src/main/java/shop/dangdang/service/S3Uploader.java
  src/main/java/shop/dangdang/testdata/TestDataRunner.java
  src/main/resources/application.properties
  src/main/resources/aws.yml
  src/main/resources/static/images/background01.png
  src/main/resources/static/images/img_section/coco.jpg
  src/main/resources/static/images/img_section/img03.jpg
  src/main/resources/static/images/temp.png
  src/main/resources/static/images/thumb.jpeg
  src/main/resources/static/images/thumb02.jpg
  src/main/resources/static/images/thumb03.jpg
  src/main/resources/static/img/img03.jpg
  src/main/resources/static/img/thumb.jpeg
  src/main/resources/static/index.html
  src/main/resources/static/registry.html
  src/main/resources/static/styles/button.css
  src/main/resources/static/styles/common.css
  src/main/resources/static/styles/detail.css
  src/main/resources/static/styles/reset.css
  src/main/resources/static/styles/style.css
  src/test/java/com/sparta/dangdang/DangdangApplicationTests.java
Labels: develop, backend

#48 [update] html 제거 & Get 일부 수정 [#37]
  src/main/java/shop/dangdang/controller/RegistryController.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/service/MembershipService.java
  src/main/java/shop/dangdang/service/RegistryService.java
  src/main/resources/static/index.html
  src/main/resources/static/registry.html
  src/main/resources/static/styles/button.css
  src/main/resources/static/styles/common.css
  src/main/resources/static/styles/detail.css
  src/main/resources/static/styles/reset.css
  src/main/resources/static/styles/style.css
Labels: develop, backend

#49 [Pull requests] main
  src/main/java/shop/dangdang/controller/RegistryController.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/service/MembershipService.java
  src/main/java/shop/dangdang/service/RegistryService.java
  src/main/resources/static/index.html
  src/main/resources/static/registry.html
  src/main/resources/static/styles/button.css
  src/main/resources/static/styles/common.css
  src/main/resources/static/styles/detail.css
  src/main/resources/static/styles/reset.css
  src/main/resources/static/styles/style.css
Labels: develop, backend

#53 [add] package명 파일 전부 통일 [#37]
  src/main/java/shop/dangdang/config/WebConfig.java
  src/main/java/shop/dangdang/controller/FeedDetailController.java
  src/main/java/shop/dangdang/domain/Comment.java
  src/main/java/shop/dangdang/domain/Feed.java
  src/main/java/shop/dangdang/domain/FeedLikeUser.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/dto/CommentResponseDto.java
  src/main/java/shop/dangdang/dto/CommonMsgResponseDto.java
  src/main/java/shop/dangdang/dto/FeedDetailResponseDto.java
  src/main/java/shop/dangdang/dto/FeedLikeRequestDto.java
  src/main/java/shop/dangdang/dto/FeedLikeResponseDto.java
  src/main/java/shop/dangdang/repository/CommentRepository.java
  src/main/java/shop/dangdang/repository/FeedLikeUserRepository.java
  src/main/java/shop/dangdang/repository/FeedRepository.java
  src/main/java/shop/dangdang/repository/UserRepository.java
  src/main/java/shop/dangdang/service/FeedDetailService.java
  src/main/java/shop/dangdang/testdata/TestDataRunner.java
Labels: develop, backend

#55 [Pull requests] main
  src/main/java/shop/dangdang/config/WebConfig.java
  src/main/java/shop/dangdang/controller/FeedDetailController.java
  src/main/java/shop/dangdang/domain/Comment.java
  src/main/java/shop/dangdang/domain/Feed.java
  src/main/java/shop/dangdang/domain/FeedLikeUser.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/dto/CommentResponseDto.java
  src/main/java/shop/dangdang/dto/CommonMsgResponseDto.java
  src/main/java/shop/dangdang/dto/FeedDetailResponseDto.java
  src/main/java/shop/dangdang/dto/FeedLikeRequestDto.java
  src/main/java/shop/dangdang/dto/FeedLikeResponseDto.java
  src/main/java/shop/dangdang/repository/CommentRepository.java
  src/main/java/shop/dangdang/repository/FeedLikeUserRepository.java
  src/main/java/shop/dangdang/repository/FeedRepository.java
  src/main/java/shop/dangdang/repository/UserRepository.java
  src/main/java/shop/dangdang/service/FeedDetailService.java
  src/main/java/shop/dangdang/testdata/TestDataRunner.java
Labels: develop, backend

#56 [add] 소연님 파트와 제 파트를 합침 [#39]
  src/main/java/shop/dangdang/controller/RegistryController.java
  src/main/java/shop/dangdang/domain/Comment.java
  src/main/java/shop/dangdang/domain/Feed.java
  src/main/java/shop/dangdang/domain/FeedLikeUser.java
  src/main/java/shop/dangdang/domain/Membership.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/repository/UserRepository.java
  src/main/java/shop/dangdang/service/FeedDetailService.java
  src/main/java/shop/dangdang/testdata/TestDataRunner.java
  src/test/java/com/sparta/dangdang/DangdangApplicationTests.java
Labels: develop, backend

#58 [update] url 수정 [#37]
  src/main/java/shop/dangdang/controller/FrontController.java
Labels: develop, backend

#59 [Pull requests] main
  src/main/java/shop/dangdang/controller/FrontController.java
Labels: develop, backend

#60 [update] entity 수정 [#37]
  src/main/java/shop/dangdang/domain/Registry.java
Labels: develop, backend

#61 [Pull requests] main
  src/main/java/shop/dangdang/domain/Registry.java
Labels: develop, backend

#64 [update] User 엔티티 삭제 [#62]
  src/main/java/shop/dangdang/domain/Comment.java
  src/main/java/shop/dangdang/domain/Feed.java
  src/main/java/shop/dangdang/domain/FeedLikeUser.java
  src/main/java/shop/dangdang/domain/Membership.java
  src/main/java/shop/dangdang/domain/User.java
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/repository/UserRepository.java
  src/main/java/shop/dangdang/service/FeedDetailService.java
  src/main/java/shop/dangdang/testdata/TestDataRunner.java
Labels: develop, backend

#71 Feature/upload [#57]
  src/main/java/shop/dangdang/controller/RegistryController.java
  src/main/java/shop/dangdang/dto/MembershipDto.java
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/repository/RegistryRepository.java
  src/main/java/shop/dangdang/service/RegistryService.java
Labels: develop, backend

#74 [update] Membership.dto 변수명 수정 [#37]
  src/main/java/shop/dangdang/dto/MembershipDto.java
Labels: develop, backend

#70 [add] JWT 로그인 및 회원가입(with 스프링시큐리티)
  build.gradle
  src/main/java/shop/dangdang/DangDangApplication.java
  src/main/java/shop/dangdang/config/SecurityConfig.java
  src/main/java/shop/dangdang/controller/FeedDetailController.java
  src/main/java/shop/dangdang/controller/JwtController.java
  src/main/java/shop/dangdang/domain/Authority.java
  src/main/java/shop/dangdang/domain/Membership.java
  src/main/java/shop/dangdang/dto/JoinDto.java
  src/main/java/shop/dangdang/dto/LoginDto.java
  src/main/java/shop/dangdang/dto/TokenDto.java
  src/main/java/shop/dangdang/jwt/JwtAccessDeniedHandler.java
  src/main/java/shop/dangdang/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/shop/dangdang/jwt/JwtFilter.java
  src/main/java/shop/dangdang/jwt/JwtSecurityConfig.java
  src/main/java/shop/dangdang/jwt/TokenProvider.java
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/service/CustomUserDetailsService.java
  src/main/java/shop/dangdang/service/FeedDetailService.java
  src/main/java/shop/dangdang/service/JwtService.java
  src/main/java/shop/dangdang/testdata/TestDataRunner.java
  src/main/java/shop/dangdang/util/SecurityUtil.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: develop, backend

#76 [add] 사소한 컴파일 에러 해결 [#75]
  src/main/java/shop/dangdang/repository/MembershipRepository.java
  src/main/java/shop/dangdang/service/RegistryService.java
Labels: bug, develop, backend

#78 [add] mainpage 백엔드파일추가 [#none]
  src/main/java/shop/dangdang/controller/MainPageController.java
  src/main/java/shop/dangdang/dto/MainPageDto.java
  src/main/java/shop/dangdang/service/MainPageService.java
Labels: backend

#79 [fix] 화면 실행과정에서 에러 해결 및 nickname db 저장 [#37]
  src/main/java/shop/dangdang/domain/Registry.java
  src/main/java/shop/dangdang/dto/RegistryDto.java
  src/main/java/shop/dangdang/service/RegistryService.java
  src/main/resources/aws.yml
  src/main/resources/static/images/background02.png
  src/main/resources/static/images/img_section/coco.jpg
  src/main/resources/static/images/img_section/img01.jpg
  src/main/resources/static/images/imgs_section/dogimg_01.jpg
  src/main/resources/static/images/imgs_section/dogimg_02.jpg
  src/main/resources/static/images/imgs_section/dogimg_03.jpg
  src/main/resources/static/images/imgs_section/dogimg_04.jpg
Labels: develop, backend
